apiVersion: v1
kind: Service
metadata:
  name: go-grpc-starter-service
spec:
  type: NodePort
  selector:
    app: go-grpc-starter
  ports:
    - protocol: TCP
      port: 8980
      targetPort: 8980
